### ISSUE TITLE
Step 2 - not triggering consistently

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/writing-javascript-actions#1]
It seems that the instructions for step 3 aren't consistently triggered, based upon when an action completes.  I believe this is a known issue.

@mattdavis0351, would we be able to post the instructions for step 3 earlier, instead of waiting on the workflow to run correctly? We could still have something wait on that step, but posting the instructions earlier may allow users to continue the course even if the action is competing for timing with Learning Lab. What do you think?

**Comment by mattdavis0351** [comment]
@brianamarie I've toyed with this section in the new Docker actions course.  I too felt like it was a bit weird so I tinkered with it.  

If you don't mind a minor delay since this is more of an odd feeling thing and not a course breaking thing, I'd love to get that finished and have you run through each initial section side-by-side so we can come up with a better way.

What do you think, another late-night/early-morning Learning Lab jam to improve this section once I roll out another option for you to test?

**Comment by brianamarie** [comment]
> this is more of an odd feeling thing and not a course breaking thing

🤔Can you help me understand how a step not triggering consistently is an odd feeling thing and not a course breaking thing?

**Comment by mattdavis0351** [comment]
@brianamarie I see what you are saying.  I meant waiting on the workflow to run has an odd feeling for the flow of the course.  There is no real reason we need to wait on that workflow, and if I recall there isn't much of a reason to even reference it, it's just initial setup.

The steps not triggering are definitely course breaking.  I think it has everything to do with how quickly the payloads move in relation to the workflow finishing and it's a race to see which payload gets to the bot first.

Usually this can be fixed by making a second commit in the pull request, which we outline in the troubleshooting steps.  Is the follow up commit not triggering the next step?

Lastly, could you point me to where we are seeing this cause problems?  Are people asking about it in the forum?  Is this just a one-off occurrence?

I ask those question because I have pointed a few people to this course and they have gotten through it without any problems with the steps so I'm trying to further understand the cause.  Right now it is only speculation that it's a payload race.

**Comment by brianamarie** [comment]
> I see what you are saying. I meant waiting on the workflow to run has an odd feeling for the flow of the course. There is no real reason we need to wait on that workflow, and if I recall there isn't much of a reason to even reference it, it's just initial setup.
> 
> The steps not triggering are definitely course breaking. I think it has everything to do with how quickly the payloads move in relation to the workflow finishing and it's a race to see which payload gets to the bot first.

👍 

> Usually this can be fixed by making a second commit in the pull request, which we outline in the troubleshooting steps. Is the follow up commit not triggering the next step?

> Lastly, could you point me to where we are seeing this cause problems? Are people asking about it in the forum? Is this just a one-off occurrence?

I thought that this was happening about 50% of the time  as we were testing the course; if that's not the case then we should close the issue.
